"""empty message

Revision ID: 391ac499c0b9
Revises: 7cc5547a166f
Create Date: 2024-02-12 13:53:38.010568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391ac499c0b9'
down_revision = '7cc5547a166f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garments_outfits',
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garment_table.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfit_table.id'], ),
    sa.PrimaryKeyConstraint('garment_id', 'outfit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garments_outfits')
    op.drop_table('outfit_table')
    # ### end Alembic commands ###
