"""empty message

Revision ID: d394484cfcae
Revises: f1d8fe081b4a
Create Date: 2024-02-13 22:10:13.452320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd394484cfcae'
down_revision = 'f1d8fe081b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garments_outfits', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('garments_outfits', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garments_outfits', 'height')
    op.drop_column('garments_outfits', 'width')
    # ### end Alembic commands ###
